<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php

    
  
  $str = '<select><option value="107">Abu Dhabi (!!! Geldig tot 2000-08-31)</option>
<option value="176">Afars en Issas (!!! Geldig tot 2000-08-31)</option>
<option value="89">Afghaanse</option>
<option value="1">Albanese</option>
<option value="163">Algerijnse</option>
<option value="277">Amerikaans-Samoa</option>
<option value="196">Amerikaanse</option>
<option value="2">Andorrese</option>
<option value="154">Angolese</option>
<option value="177">Angolese (!!! Geldig tot 2005-08-31)</option>
<option value="228">Anguillaanse (Anguilla)</option>
<option value="229">Antigua (inwoner van)</option>
<option value="237">Argentijnse</option>
<option value="87">Armeense</option>
<option value="253">Australische</option>
<option value="88">Azerbeidzjaanse</option>
<option value="211">Bahamaanse</option>
<option value="222">Bahamase (!!! Geldig tot 2005-08-31)</option>
<option value="106">Bahreinse</option>
<option value="86">Bangladese</option>
<option value="209">Barbados</option>
<option value="171">Belgisch Kongo (!!! Geldig tot 1999-12-31)</option>
<option value="50">Belgische</option>
<option value="227">Belize (V.K.) (!!! Geldig tot 2000-08-31)</option>
<option value="216">Belizische</option>
<option value="124">Beninse</option>
<option value="223">Bermudaanse</option>
<option value="77">Bhutaanse</option>
<option value="238">Boliviaanse</option>
<option value="192">Bophutatswaanse (!!! Geldig tot 2000-08-31)</option>
<option value="49">Bosnisch-Herzegovinse</option>
<option value="116">Botswaanse</option>
<option value="239">Braziliaanse</option>
<option value="251">Brits Honduras (!!! Geldig tot 2000-08-31)</option>
<option value="12">Britse</option>
<option value="210">Britse Antillen (!!! Geldig tot 2000-08-31)</option>
<option value="78">Bruneise</option>
<option value="6">Bulgaarse</option>
<option value="122">Burkinese</option>
<option value="290">Burkinese (!!! Geldig tot 2000-08-31)</option>
<option value="117">Burundese</option>
<option value="178">Cabinda (!!! Geldig tot 2000-08-31)</option>
<option value="67">Cambodjaanse</option>
<option value="283">Cambodjaanse (!!! Geldig tot 2005-08-31)</option>
<option value="439">Cambodjaanse (oude code)                toegevoegd na rollback BLADC59 (!!! Geldig tot 1901-01-02)</option>
<option value="195">Canadese</option>
<option value="193">Canarische Eilanden (S.) (!!! Geldig tot 2000-08-31)</option>
<option value="267">Carolinische (!!! Geldig tot 2000-08-31)</option>
<option value="230">Caymaneilanden</option>
<option value="119">Centraal-Afrikaanse</option>
<option value="285">Ceylonese (!!! Geldig tot 2000-08-31)</option>
<option value="240">Chileense</option>
<option value="72">Chinese</option>
<option value="241">Colombiaanse</option>
<option value="156">Comorese</option>
<option value="182">Comorese (!!! Geldig tot 2005-08-31)</option>
<option value="121">Congolese (Brazzaville)</option>
<option value="120">Congolese (Kinshasa; ex-Zaïre)</option>
<option value="274">Cookeilanden</option>
<option value="197">Costaricaanse</option>
<option value="198">Cubaanse</option>
<option value="7">Cypriotische</option>
<option value="291">Dahomese (!!! Geldig tot 2000-08-31)</option>
<option value="8">Deense</option>
<option value="158">Djiboutiaanse</option>
<option value="213">Dominica (Eiland)</option>
<option value="218">Dominica (Eiland) (!!! Geldig tot 2005-08-31)</option>
<option value="206">Dominicaanse</option>
<option value="3">Duitse</option>
<option value="34">Duitse (!!! Geldig tot 2005-08-31)</option>
<option value="55">Duitsland (!!! Geldig tot 1901-01-01)</option>
<option value="52">Duitsland (Dem.rep.) (!!! Geldig tot 2000-08-31)</option>
<option value="242">Ecuadoriaanse</option>
<option value="164">Egyptische</option>
<option value="150">Equatoriaal-Guinese</option>
<option value="162">Eritrese</option>
<option value="36">Estlandse</option>
<option value="125">Ethiopische</option>
<option value="249">Falklandeilanden</option>
<option value="188">Fernando Poo (!!! Geldig tot 2000-08-31)</option>
<option value="258">Fijaanse</option>
<option value="70">Filipijnse</option>
<option value="10">Finse</option>
<option value="296">Frans Polynesische (!!! Geldig tot 2005-08-31)</option>
<option value="250">Frans-Guyana</option>
<option value="271">Frans-Polynesische</option>
<option value="11">Franse</option>
<option value="219">Franse Antillen (!!! Geldig tot 2000-08-31)</option>
<option value="126">Gabonese</option>
<option value="127">Gambiaanse</option>
<option value="280">Gebied afhankelijk Australië (!!! Geldig tot 2000-08-31)</option>
<option value="281">Gebied afhankelijk van Nieuw-Zeeland (!!! Geldig tot 2000-08-31)</option>
<option value="91">Georgische</option>
<option value="128">Ghanese</option>
<option value="56">Gibraltar</option>
<option value="212">Grenadiaanse (Grenada)</option>
<option value="14">Griekse</option>
<option value="236">Groenlandse</option>
<option value="278">Grondgebied onder Amerikaanse voogdij (!!! Geldig tot 2000-08-31)</option>
<option value="234">Guadeloupse (Guadeloupe)</option>
<option value="268">Guamese (Guam)</option>
<option value="199">Guatemalaanse</option>
<option value="151">Guinee-Bissause</option>
<option value="129">Guinese</option>
<option value="247">Guyanese</option>
<option value="205">Haïtiaanse</option>
<option value="269">Hawaïaanse (!!! Geldig tot 2000-08-31)</option>
<option value="200">Hondurese</option>
<option value="111">Hong-Kong (V.K.) (!!! Geldig tot 2000-08-31)</option>
<option value="15">Hongaarse</option>
<option value="38">Hongarije (Republiek) (!!! Geldig tot 1901-01-01)</option>
<option value="84">Hongkongse</option>
<option value="16">Ierse</option>
<option value="17">IJslandse</option>
<option value="63">Indische</option>
<option value="287">Indische (!!! Geldig tot 2000-08-31)</option>
<option value="64">Indonesische</option>
<option value="92">Iraakse</option>
<option value="93">Iraanse</option>
<option value="94">Israëlische</option>
<option value="28">Italiaanse</option>
<option value="123">Ivoriaanse</option>
<option value="201">Jamaïcaanse</option>
<option value="65">Japanese</option>
<option value="101">Jemenitische (!!! Geldig tot 2000-08-31)</option>
<option value="108">Jemenitische</option>
<option value="51">Joegoslavië (!!! Geldig tot 1901-01-01)</option>
<option value="95">Jordaanse</option>
<option value="152">Kaapverdische</option>
<option value="181">Kaapverdische (!!! Geldig tot 2005-08-31)</option>
<option value="118">Kameroense</option>
<option value="284">Kampuchese (!!! Geldig tot 2000-08-31)</option>
<option value="79">Kazachse</option>
<option value="149">Keniase</option>
<option value="58">Khmerische (!!! Geldig tot 2000-08-31)</option>
<option value="80">Kirgizische</option>
<option value="263">Kiribatiaanse</option>
<option value="295">Kiribatiaanse (!!! Geldig tot 2005-08-31)</option>
<option value="232">Kitts en Nevis (V.K.) (!!! Geldig tot 2000-08-31)</option>
<option value="102">Koeweitse</option>
<option value="174">Kongo (!!! Geldig tot 2000-08-31)</option>
<option value="435">Kosovaarse</option>
<option value="46">Kroatische</option>
<option value="66">Laotische</option>
<option value="115">Lesothaanse</option>
<option value="35">Letse</option>
<option value="96">Libanese</option>
<option value="132">Liberiaanse</option>
<option value="165">Libische</option>
<option value="18">Liechtensteinse</option>
<option value="37">Litouwse</option>
<option value="13">Luxemburgse</option>
<option value="221">Maagdeneilanden (Amerikaanse)</option>
<option value="224">Maagdeneilanden (Britse)</option>
<option value="112">Macao (inwoner van)</option>
<option value="48">Macedonische (Ex-Joeg.)</option>
<option value="194">Madeira (!!! Geldig tot 2000-08-31)</option>
<option value="138">Malagasische</option>
<option value="170">Malawische</option>
<option value="76">Maldivische</option>
<option value="68">Maleise</option>
<option value="133">Malinese</option>
<option value="19">Maltese</option>
<option value="166">Marokkaanse</option>
<option value="442">Marshalleilandse</option>
<option value="235">Martinikaanse (Martinique)</option>
<option value="167">Mauritaanse (Mauritanië)</option>
<option value="131">Mauritiaanse (Mauritius Eil.)</option>
<option value="427">Mayotte (inwoner van)</option>
<option value="202">Mexicaanse</option>
<option value="441">Micronesische</option>
<option value="44">Moldavische</option>
<option value="20">Monegaskische</option>
<option value="75">Mongoolse</option>
<option value="425">Montenegrijnse</option>
<option value="231">Montserrataanse</option>
<option value="179">Mozambicaanse (!!! Geldig tot 2005-08-31)</option>
<option value="153">Mozambikaanse</option>
<option value="57">Myanmarese</option>
<option value="180">Namibische</option>
<option value="424">nationaliteit onbekend (!!! Geldig tot 2003-01-31)</option>
<option value="444">Nationaliteit onbekend</option>
<option value="436">Nationaliteitscode onbekend</option>
<option value="437">Nationaliteitscode onbekend (!!! Geldig tot 2011-07-13)</option>
<option value="440">Nationaliteitscode Zuid Soedan</option>
<option value="256">Nauruaanse</option>
<option value="298">NAVO</option>
<option value="252">Nederlands Guyana (!!! Geldig tot 2000-08-31)</option>
<option value="29">Nederlandse</option>
<option value="220">Nederlandse Antillen</option>
<option value="69">Nepalese</option>
<option value="294">Ngwanese (!!! Geldig tot 2000-08-31)</option>
<option value="203">Nicaraguaanse</option>
<option value="270">Nieuw-Caledonische</option>
<option value="254">Nieuw-Zeelandse</option>
<option value="259">Nieuwhebridense (!!! Geldig tot 2000-08-31)</option>
<option value="135">Nigerese</option>
<option value="136">Nigeriaanse</option>
<option value="272">Niue (inwoner van)</option>
<option value="73">Noord-Koreaanse</option>
<option value="428">Noordelijke Marianen (inwoner van)</option>
<option value="21">Noorse</option>
<option value="137">Oegandese</option>
<option value="43">Oekraïnse</option>
<option value="81">Oezbeekse</option>
<option value="104">Omaanse</option>
<option value="289">Omaanse (!!! Geldig tot 2000-08-31)</option>
<option value="438">Oost Timor</option>
<option value="113">Oost-Timorese (Timor-Leste)</option>
<option value="4">Oostduitse (!!! Geldig tot 2000-08-31)</option>
<option value="5">Oostenrijkse</option>
<option value="130">Oppervoltaanse (!!! Geldig tot 2000-08-31)</option>
<option value="300">OVN-onbepaald (!!! Geldig tot 2005-08-31)</option>
<option value="299">OVN-vluchteling (!!! Geldig tot 2005-08-31)</option>
<option value="97">Pakistaanse</option>
<option value="266">Palau (inwoner van)</option>
<option value="114">Palestijnse</option>
<option value="109">Palestina (!!! Geldig tot 1901-01-01)</option>
<option value="204">Panamese</option>
<option value="260">Papoeaanse</option>
<option value="243">Paraguayaanse</option>
<option value="244">Peruaanse</option>
<option value="279">Pitcairneilanden</option>
<option value="282">Politiek Vluchteling (!!! Geldig tot 2005-08-31)</option>
<option value="22">Poolse (!!! Geldig tot 2005-08-31)</option>
<option value="39">Poolse</option>
<option value="187">Portugees Guinea (!!! Geldig tot 2000-08-31)</option>
<option value="23">Portugese</option>
<option value="225">Puertoricaanse</option>
<option value="105">Qatarese</option>
<option value="423">regularisatieaanvraag ingediend, nog geen formeel bewijs van nationaliteit (!!! Geldig tot 1901-01-01)</option>
<option value="183">Réunionse</option>
<option value="140">Rhodesische (!!! Geldig tot 2000-08-31)</option>
<option value="172">Roeanda (!!! Geldig tot 2000-08-31)</option>
<option value="24">Roemeense</option>
<option value="45">Russische</option>
<option value="141">Rwandese</option>
<option value="184">Saharaanse</option>
<option value="217">Saint Kitts en Nevis (inwoner van)</option>
<option value="215">Saint Vincent (inwoner van)</option>
<option value="214">Saint-Luciaanse</option>
<option value="233">Saint-Pierre en Miquelon (inwoner van)</option>
<option value="264">Salomonseilanden (inwoner van)</option>
<option value="207">Salvadoriaanse</option>
<option value="255">Samoaanse</option>
<option value="25">Sanmarinese</option>
<option value="189">Santhomé (Eiland van) (!!! Geldig tot 2000-08-31)</option>
<option value="159">Sao Tomé en Principe</option>
<option value="90">Saoedische</option>
<option value="293">Saotomese (!!! Geldig tot 2005-08-31)</option>
<option value="134">Senegalese</option>
<option value="161">Senegambia (!!! Geldig tot 2000-08-31)</option>
<option value="32">Servisch-Montenegrijnse (ex-Joegoslavië) (!!! Geldig tot 2006-08-31)</option>
<option value="426">Servische</option>
<option value="155">Seychelse</option>
<option value="186">Seychelse (!!! Geldig tot 2005-08-31)</option>
<option value="297">Shape</option>
<option value="142">Sierraleoonse</option>
<option value="288">Sikkimese (!!! Geldig tot 2000-08-31)</option>
<option value="61">Singaporese</option>
<option value="185">Sint-Helena (inwoner van)</option>
<option value="41">Slovaakse</option>
<option value="47">Sloveense</option>
<option value="168">Soedanese</option>
<option value="143">Somalische</option>
<option value="31">Sovjetrussische (!!! Geldig tot 2000-08-31)</option>
<option value="9">Spaanse</option>
<option value="59">Srilankaanse</option>
<option value="261">Stille Oceaan /Eilanden/ (!!! Geldig tot 2000-08-31)</option>
<option value="248">Surinaamse</option>
<option value="160">Swaziland (!!! Geldig tot 1901-01-01)</option>
<option value="190">Swaziliaanse (!!! Geldig tot 2005-08-31)</option>
<option value="144">Swazische (Swaziland)</option>
<option value="99">Syrische</option>
<option value="82">Tadzjiekse</option>
<option value="275">Tahiti (!!! Geldig tot 2000-08-31)</option>
<option value="60">Taiwanese</option>
<option value="286">Taiwanese (!!! Geldig tot 2005-08-31)</option>
<option value="145">Tanzaniaanse</option>
<option value="85">Thaïse</option>
<option value="147">Togolese</option>
<option value="273">Tokelau (inwoner van)</option>
<option value="257">Tongaanse (Tonga)</option>
<option value="191">Transkeise (!!! Geldig tot 2000-08-31)</option>
<option value="208">Trinidadse</option>
<option value="146">Tsjadische</option>
<option value="30">Tsjechische (!!! Geldig tot 2000-08-31)</option>
<option value="40">Tsjechische</option>
<option value="53">Tsjecho-Slowakije (!!! Geldig tot 2000-08-31)</option>
<option value="169">Tunesische</option>
<option value="83">Turkmeense</option>
<option value="226">Turks- en Caicoseilanden (inwoner van)</option>
<option value="100">Turkse</option>
<option value="262">Tuvaluaanse</option>
<option value="54">Unie der Socialistische Sovjetrepublieken (!!! Geldig tot 2000-08-31)</option>
<option value="245">Uruguayaanse</option>
<option value="173">Urundi (!!! Geldig tot 2000-08-31)</option>
<option value="422">Vaderlandsloos/Staatloos</option>
<option value="265">Vanuatuaanse</option>
<option value="33">Vatikaanse</option>
<option value="246">Venezolaanse</option>
<option value="98">Verenigde Arabische Emiraten (inw. van)</option>
<option value="74">Viëtnamese</option>
<option value="419">vluchteling afk. uit de Ver. Arab. Emir.</option>
<option value="400">vluchteling afkomstig uit Burkina Faso</option>
<option value="399">vluchteling afkomstig uit Gaboen</option>
<option value="405">vluchteling afkomstig uit Ivoorkust</option>
<option value="404">vluchteling afkomstig uit Nepal</option>
<option value="398">vluchteling afkomstig uit Sierra Leon</option>
<option value="292">Vluchteling onbepaald</option>
<option value="376">vluchteling van Afghaanse herkomst</option>
<option value="307">vluchteling van Albanese herkomst</option>
<option value="367">vluchteling van Algerijnse herkomst</option>
<option value="351">vluchteling van Angolese herkomst</option>
<option value="304">vluchteling van Argentijnse herkomst</option>
<option value="337">vluchteling van Armeense herkomst</option>
<option value="409">vluchteling van Azerbaidzjaanse herkomst</option>
<option value="430">vluchteling van Bahreinse herkomst</option>
<option value="391">vluchteling van Bangladeshische herkomst</option>
<option value="394">vluchteling van Benijnse herkomst</option>
<option value="418">vluchteling van Bhutanese herkomst</option>
<option value="380">vluchteling van Birmaanse herkomst</option>
<option value="359">vluchteling van Boliviaanse herkomst</option>
<option value="407">vluchteling van Bosnische herkomst</option>
<option value="353">vluchteling van Braziliaanse herkomst</option>
<option value="310">vluchteling van Bulgaarse herkomst</option>
<option value="347">vluchteling van Burundische herkomst</option>
<option value="306">vluchteling van Cambodjaanse herkomst</option>
<option value="416">vluchteling van Centraalafrikaanse herkomst</option>
<option value="305">vluchteling van Chileense herkomst</option>
<option value="338">vluchteling van Chinese herkomst</option>
<option value="370">vluchteling van Columbiaanse herkomst</option>
<option value="413">vluchteling van Congolese herkomst</option>
<option value="311">vluchteling van Croatische herkomst</option>
<option value="339">vluchteling van Cubaanse herkomst</option>
<option value="421">vluchteling van Djiboutiaanse herkomst</option>
<option value="303">vluchteling van Dominicaanse herkomst</option>
<option value="308">vluchteling van Duitse herkomst</option>
<option value="390">vluchteling van Ecuadoriaanse herkomst</option>
<option value="340">vluchteling van Egyptische herkomst</option>
<option value="434">vluchteling van Eritrese herkomst</option>
<option value="314">vluchteling van Estische herkomst</option>
<option value="355">vluchteling van Ethiopische herkomst</option>
<option value="389">vluchteling van Filippijnse herkomst</option>
<option value="315">vluchteling van Finse herkomst</option>
<option value="363">vluchteling van Franse herkomst</option>
<option value="316">vluchteling van Georgische herkomst</option>
<option value="369">vluchteling van Ghanese herkomst</option>
<option value="317">vluchteling van Griekse herkomst</option>
<option value="383">vluchteling van Guatemalaanse herkomst</option>
<option value="431">vluchteling van Guineebissause herkomst</option>
<option value="357">vluchteling van Guinese herkomst</option>
<option value="360">vluchteling van Guyanese herkomst</option>
<option value="349">vluchteling van Haïtiaanse herkomst</option>
<option value="329">vluchteling van herkomst uit de U.S.S.R.</option>
<option value="312">vluchteling van herkomstig uit vrijstaat Danzig</option>
<option value="318">vluchteling van Hongaarse herkomst</option>
<option value="386">vluchteling van Indische herkomst</option>
<option value="356">vluchteling van Indonesische herkomst</option>
<option value="341">vluchteling van Iraakse herkomst</option>
<option value="373">vluchteling van Iraanse herkomst</option>
<option value="368">vluchteling van Israëlische herkomst</option>
<option value="319">vluchteling van Italiaanse herkomst</option>
<option value="346">vluchteling van Jemenitische herkomst</option>
<option value="330">vluchteling van Joegoslavische herkomst</option>
<option value="354">vluchteling van Jordaanse herkomst</option>
<option value="384">vluchteling van Kaapverdische herkomst</option>
<option value="392">vluchteling van Kameroenische herkomst</option>
<option value="429">vluchteling van Kazakhstaanse herkomst</option>
<option value="411">vluchteling van Keniaanse herkomst</option>
<option value="361">vluchteling van Khmerische herkomst</option>
<option value="433">vluchteling van Kirgizische origine</option>
<option value="420">vluchteling van Koeweitse herkomst</option>
<option value="336">vluchteling van Kongolese herkomst</option>
<option value="362">vluchteling van Koreaanse herkomst</option>
<option value="358">vluchteling van Laotische herkomst</option>
<option value="320">vluchteling van Letse herkomst</option>
<option value="342">vluchteling van Libanese herkomst</option>
<option value="403">vluchteling van Liberiaanse herkomst</option>
<option value="385">vluchteling van Libische herkomst</option>
<option value="321">vluchteling van Litouwse herkomst</option>
<option value="348">vluchteling van Macedonische herkomst</option>
<option value="381">vluchteling van Malagassische herkomst</option>
<option value="387">vluchteling van Maleise herkomst</option>
<option value="415">vluchteling van Malinese herkomst</option>
<option value="352">vluchteling van Marrokkaanse herkomst</option>
<option value="402">vluchteling van Mauritaanse herkomst</option>
<option value="412">vluchteling van Moldavische herkomst</option>
<option value="379">vluchteling van Mozambiekse herkomst</option>
<option value="432">vluchteling van Myanmarese herkomst</option>
<option value="382">vluchteling van Namibische herkomst</option>
<option value="397">vluchteling van Nicaraguaanse herkomst</option>
<option value="406">vluchteling van Nigeraanse herkomst</option>
<option value="350">vluchteling van Nigeriaanse herkomst</option>
<option value="332">vluchteling van Oegandese herkomst</option>
<option value="328">vluchteling van Oekraïense herkomst</option>
<option value="408">vluchteling van Oezbekistaanse herkomst</option>
<option value="309">vluchteling van Oostenrijkse herkomst</option>
<option value="333">vluchteling van Pakistaanse herkomst</option>
<option value="343">vluchteling van Palestijnse herkomst</option>
<option value="443">vluchteling van Palestijnse herkomst(oudtoegevoegd na rollback BLADC59 (!!! Geldig tot 1901-01-02)</option>
<option value="395">vluchteling van Panamese herkomst</option>
<option value="365">vluchteling van Paraguyaanse herkomst</option>
<option value="364">vluchteling van Peruaanse herkomst</option>
<option value="322">vluchteling van Poolse herkomst</option>
<option value="323">vluchteling van Portugese herkomst</option>
<option value="324">vluchteling van Roemeense herkomst</option>
<option value="331">vluchteling van Ruandese herkomst</option>
<option value="325">vluchteling van Russische herkomst</option>
<option value="374">vluchteling van Salvadoriaanse herkomst</option>
<option value="371">vluchteling van Saoedische herkomst</option>
<option value="410">vluchteling van Senegalese herkomst</option>
<option value="326">vluchteling van Servische herkomst</option>
<option value="414">vluchteling van Sloveense herkomst</option>
<option value="378">vluchteling van Soedanese herkomst</option>
<option value="375">vluchteling van Somalische herkomst</option>
<option value="313">vluchteling van Spaanse herkomst</option>
<option value="393">vluchteling van Srilankaanse herkomst</option>
<option value="344">vluchteling van Syrische herkomst</option>
<option value="366">vluchteling van Tanzaniaanse herkomst</option>
<option value="388">vluchteling van Thaïse herkomst</option>
<option value="396">vluchteling van Tibetaanse herkomst</option>
<option value="401">vluchteling van Togose herkomst</option>
<option value="377">vluchteling van Tsjadische herkomst</option>
<option value="327">vluchteling van Tsjechische herkomst</option>
<option value="301">vluchteling van Tunesische herkomst</option>
<option value="345">vluchteling van Turkse herkomst</option>
<option value="302">vluchteling van Uruguayaanse herkomst</option>
<option value="334">vluchteling van Viëtnamese herkomst</option>
<option value="417">vluchteling van Witrussische herkomst</option>
<option value="335">vluchteling van Zaïrese herkomst</option>
<option value="372">vluchteling van Zuidafrikaanse herkomst</option>
<option value="276">Wallis en Futuna (inwoner van)</option>
<option value="42">Witrussische (Bielorusland)</option>
<option value="175">Zaïrese (Rep.) (!!! Geldig tot 2000-08-31)</option>
<option value="148">Zambiaanse</option>
<option value="157">Zimbabwaanse</option>
<option value="139">Zuid-Afrikaanse</option>
<option value="62">Zuid-Koreaanse</option>
<option value="110">Zuid-Viëtnam (!!! Geldig tot 2000-08-31)</option>
<option value="103">Zuidjemenitische (!!! Geldig tot 2000-08-31)</option>
<option value="71">Zuidviëtnamese (!!! Geldig tot 2000-08-31)</option>
<option value="26">Zweedse</option>
<option value="27">Zwitserse</option>
</select>';


//preg_match_all("/<option/",$str,$matches);

preg_match_all("/<option value=\"([0-9]+)\">([A-Za-z0-9\s\(\)\/=;\"!_.äëüïöâêûîôèàùìòáéúíóÄËÜÏÖÂÊÛÎÔÀÈÙÌÒÁÉÚÍÓ'-]*)<\/option>/",$str,$matches);


$dbh = new MyPDO();

foreach($matches[2] as $key => $nationaliteit){
    
    echo $matches[1][$key] . " - " . $nationaliteit . "<br>";
    
    $sth = $dbh->prepare("INSERT INTO nationaliteiten (`id`,`nationaliteit`) VALUES (:ID, :NAT)");
    $sth->bindValue(":ID",$matches[1][$key],PDO::PARAM_INT);
    $sth->bindValue(":NAT",$nationaliteit,PDO::PARAM_STR);
    $sth->execute();
    
}
  
?>
